[project]
name = "openmm-cli"
version = "0.1.0"
description = "Command line interface for running OpenMM simulations"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "mdtraj>=1.11.1.post1",
    "numpy>=2.4.2",
    "openmm[cuda12]>=8.5",
    "pdbfixer>=1.12.0",
    "pydantic>=2.12.5",
    "pyyaml>=6.0.3",
    "typer>=0.24.1",
]
[project.scripts]
openmm-cli = "openmm_cli.cli:app"
[project.urls]
Documentation = "https://jankocivic.github.io/openmm-cli/"

[tool.uv]
package = true

[dependency-groups]
dev = [
    "black>=26.3.0",
    "pytest>=9.0.2",
    "ruff>=0.15.5",
]
docs = [
    "mkdocs>=1.6.1,<2",
    "mkdocs-material>=9.7.6",
    "mkdocs-typer2>=0.3.0",
    "mkdocstrings[python]>=1.0.4",
]

[tool.black]
target-version = ["py311"]
line-length = 88
