"""The :class:`Runner` ties the building blocks together and drives the stages.

It owns the live ``Simulation`` (built by :func:`~.system.build_simulation`),
exposes its ``system`` and ``topology`` to stages, and executes each configured
stage in order, resetting per-stage bookkeeping between them.
"""

from __future__ import annotations

import yaml
from openmm import app

from .config import Config
from .system import build_simulation


class Runner:
    def __init__(self, cfg: Config) -> None:
        self.cfg = cfg
        self.output_dir = cfg.output_dir
        self.simulation: app.Simulation | None = None

    @property
    def system(self):
        """The OpenMM ``System`` (owned by the simulation)."""
        return self.simulation.system

    @property
    def topology(self):
        """The OpenMM ``Topology`` (owned by the simulation)."""
        return self.simulation.topology

    def setup(self) -> None:
        """Build the starting simulation and report what was set up."""
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self._write_resolved_config()
        self._announce_coordinate_source()

        self.simulation = build_simulation(self.cfg)

        print(
            f"System: {self.system.getNumParticles()} particles, "
            f"{self.system.getNumConstraints()} constraints"
        )
        print(
            f"Platform: {self.simulation.context.getPlatform().getName()} "
            f"({self.cfg.platform.precision} precision)"
        )

    def run(self) -> None:
        """Build the simulation if needed and execute every stage in order."""
        if self.simulation is None:
            self.setup()
        for stage in self.cfg.stages:
            print(f"\n=== Stage: {stage.name} ({stage.type}) ===")
            stage.run(self)
            self._reset_after_stage()
        print("\nAll stages complete.")

    def _reset_after_stage(self) -> None:
        """Clear per-stage bookkeeping so the next stage starts clean."""
        self.simulation.reporters.clear()
        self.simulation.currentStep = 0
        self.simulation.context.setTime(0)

    def _announce_coordinate_source(self) -> None:
        system = self.cfg.system
        source = system.restart_from or system.coordinates or system.topology
        print(f"Loading coordinates from {source}")

    def _write_resolved_config(self) -> None:
        """Dump the fully-resolved config (user inputs + defaults) for the record."""
        path = self.output_dir / "resolved_config.yaml"
        resolved = self.cfg.model_dump(mode="json")
        header = (
            "# Auto-generated by `openmm-cli run`.\n"
            "# The complete configuration used for this run: every value supplied\n"
            "# by the user plus all defaults filled in for anything left unset.\n"
        )
        with open(path, "w") as f:
            f.write(header)
            yaml.safe_dump(resolved, f, sort_keys=False, default_flow_style=False)
        print(f"Wrote resolved configuration to {path}")
