"""The :class:`Runner` drives the stages, rebuilding the simulation per stage.

Between stages only the OpenMM ``State`` (positions, velocities, box vectors) is
carried forward; each stage's simulation is built fresh from the run ``defaults``
plus that stage's overrides. A ``branch`` stage reruns the remaining stages once
per copy from the same state, into per-branch subdirectories. See
``REBUILD_PLAN.md``.
"""

from __future__ import annotations

import openmm as mm
import yaml

from .config import Config, merge_defaults
from .stage_types import SimulationStage


class Runner:
    def __init__(self, cfg: Config, simulation=None, output_dir=None) -> None:
        self.cfg = cfg
        self.simulation = simulation          # the current stage's Simulation, or None
        self.output_dir = output_dir if output_dir is not None else cfg.output_dir

    @property
    def system(self):
        """The OpenMM ``System`` of the current stage's simulation."""
        return self.simulation.system

    @property
    def topology(self):
        """The OpenMM ``Topology`` of the current stage's simulation."""
        return self.simulation.topology

    def run(self) -> None:
        """Execute every stage, rebuilding a fresh simulation for each."""
        self.cfg.output_dir.mkdir(parents=True, exist_ok=True)
        self._write_resolved_config()
        self._announce_coordinate_source()

        state = None
        if self.cfg.system.restart_from is not None:
            with open(self.cfg.system.restart_from) as f:
                state = mm.XmlSerializer.deserialize(f.read())

        self._run_stages(self.cfg.stages, state, self.cfg.output_dir)
        print("\nAll stages complete.")

    def _run_stages(self, stages, state, out_dir) -> None:
        """Run ``stages`` in order, threading the carried ``State`` between them."""
        for i, stage in enumerate(stages):
            if stage.type == "branch":
                print(f"\n=== Branch: {stage.name} (x{stage.count}) ===")
                for j in range(stage.count):
                    self._run_stages(
                        stages[i + 1:], state, out_dir / f"{stage.name}_{j}"
                    )
                return  # a branch consumes the remaining stages

            print(f"\n=== Stage: {stage.name} ({stage.type}) ===")
            out_dir.mkdir(parents=True, exist_ok=True)
            self.output_dir = out_dir

            if isinstance(stage, SimulationStage):
                defaults = merge_defaults(self.cfg.defaults, stage.defaults)
                self.simulation = stage.build(self.cfg, defaults, state)
                stage.run(self)
                state = self.simulation.context.getState(
                    getPositions=True, getVelocities=True
                )
                with open(out_dir / f"{stage.name}.xml", "w") as f:
                    f.write(mm.XmlSerializer.serialize(state))
            else:  # non-simulation stage (e.g. analysis): state unchanged
                self.simulation = None
                stage.run(self)

    def _announce_coordinate_source(self) -> None:
        system = self.cfg.system
        source = system.restart_from or system.coordinates or system.topology
        print(f"Loading coordinates from {source}")

    def _write_resolved_config(self) -> None:
        """Dump the fully-resolved config (user inputs + defaults) for the record."""
        path = self.cfg.output_dir / "resolved_config.yaml"
        resolved = self.cfg.model_dump(mode="json")
        header = (
            "# Auto-generated by `openmm-cli run`.\n"
            "# The complete configuration used for this run: every value supplied\n"
            "# by the user plus all defaults filled in for anything left unset.\n"
        )
        with open(path, "w") as f:
            f.write(header)
            yaml.safe_dump(resolved, f, sort_keys=False, default_flow_style=False)
        print(f"Wrote resolved configuration to {path}")
