"""The :class:`Runner` drives the stages, rebuilding the simulation per stage.

Between stages only the OpenMM ``State`` (positions, velocities, box vectors) is
carried forward; each stage's simulation is built fresh from the run ``defaults``
plus that stage's overrides. A ``branch`` stage reruns the remaining stages once
per copy from the same state, into per-branch subdirectories.

Re-running into an existing ``output_dir`` resumes automatically: any stage whose
end-state ``{name}.xml`` is already present is skipped and its saved state carried
forward, so an interrupted run continues from the last completed stage. (The
config is assumed unchanged -- it is the user's responsibility to use a fresh
``output_dir`` when the config changes.)
"""

from __future__ import annotations

import os

import openmm as mm
import yaml

from .config import Config
from .defaults import merge_defaults
from .stage_types import SimulationStage
from .stage_types.branch import BranchStage


class Runner:
    def __init__(self, cfg: Config) -> None:
        self.cfg = cfg
        self.simulation = None          # the current stage's Simulation, or None
        self.output_dir = cfg.output_dir

    @property
    def topology(self):
        """The OpenMM ``Topology`` of the current stage's simulation."""
        return self.simulation.topology

    def run(self) -> None:
        """Execute every stage, rebuilding a fresh simulation for each."""
        self.cfg.output_dir.mkdir(parents=True, exist_ok=True)
        self._write_resolved_config()
        self._announce_coordinate_source()

        state = None
        if self.cfg.system.restart_from is not None:
            with open(self.cfg.system.restart_from) as f:
                state = mm.XmlSerializer.deserialize(f.read())

        self._run_stages(self.cfg.stages, state, self.cfg.output_dir)
        print("\nAll stages complete.")

    def _run_stages(self, stages, state, out_dir) -> None:
        """Run ``stages`` in order, threading the carried ``State`` between them."""
        for i, stage in enumerate(stages):
            if isinstance(stage, BranchStage):
                print(f"\n=== Branch: {stage.name} (x{stage.count}) ===")
                for j in range(stage.count):
                    branch_dir = out_dir / f"{stage.name}_{j}"
                    self._run_stages(stages[i + 1:], state, branch_dir)
                return  # a branch consumes the remaining stages

            print(f"\n=== Stage: {stage.name} ({stage.type}) ===")
            out_dir.mkdir(parents=True, exist_ok=True)
            self.output_dir = out_dir

            if isinstance(stage, SimulationStage):
                state_path = out_dir / f"{stage.name}.xml"
                if state_path.exists():
                    # Resume: this stage finished on a previous run. Skip it and
                    # carry its saved end state forward to the next stage.
                    print(f"  Already complete; resuming from {state_path.name}")
                    state = mm.XmlSerializer.deserialize(state_path.read_text())
                    continue
                defaults = merge_defaults(self.cfg.defaults, stage.defaults)
                self.simulation = stage.build(self.cfg, defaults, state)
                # `setState` carried the step count and clock forward; zero them
                # so each stage's reporters count from 0 (progress, time, etc.).
                self.simulation.currentStep = 0
                self.simulation.context.setTime(0)
                stage.run(self)
                state = self.simulation.context.getState(
                    getPositions=True, getVelocities=True
                )
                self._save_state(state, state_path)
            else:  # non-simulation stage (e.g. analysis): state unchanged
                self.simulation = None
                stage.run(self)

    def _save_state(self, state, path) -> None:
        """Write a stage's end ``State`` to ``path`` atomically.

        Serializes to a temp file and ``os.replace``-s it into place, so a crash
        mid-write can never leave a partial ``{stage}.xml`` that a later resume
        would mistake for a completed stage.
        """
        tmp = path.with_name(path.name + ".tmp")
        with open(tmp, "w") as f:
            f.write(mm.XmlSerializer.serialize(state))
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)

    def _announce_coordinate_source(self) -> None:
        system = self.cfg.system
        source = system.restart_from or system.coordinates or system.topology
        print(f"Loading coordinates from {source}")

    def _write_resolved_config(self) -> None:
        """Dump the fully-resolved config (user inputs + defaults) for the record."""
        path = self.cfg.output_dir / "resolved_config.yaml"
        resolved = self.cfg.model_dump(mode="json")
        header = (
            "# Auto-generated by `openmm-cli run`.\n"
            "# The complete configuration used for this run: every value supplied\n"
            "# by the user plus all defaults filled in for anything left unset.\n"
        )
        with open(path, "w") as f:
            f.write(header)
            yaml.safe_dump(resolved, f, sort_keys=False, default_flow_style=False)
        print(f"Wrote resolved configuration to {path}")
